--- 
project_name: pg
project_homepage: http://bitbucket.org/ged/ruby-pg/
project_summary: A Ruby interface to the PostgreSQL RDBMS
project_description: |-
  This is the extension library to access a PostgreSQL database from Ruby.
  This library works with PostgreSQL 7.4 and later.
project_pubhost: deveiate.org
project_pubdir: /usr/local/www/public/code/
project_licenses: 
- Ruby
- GPL
- BSD
gem_pubhost: rubygems.org
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
release_smtphost: mail.faeriemud.org
post_install_message: ""
authors: 
  Jeff Davis: ruby-pg@j-davis.com
  Michael Granger: ged@FaerieMUD.org
project_dependencies: {}
dev_dependencies: 
  rake-compiler: ~>0.7.0
project_requirements: 
  PostgreSQL: ">=7.4"
additional_pkgfiles: 
- README.*
- GPL
- BSD
- Contributors
excluded_pkgfiles: []

required_ruby_version: ">=1.8.7"
version_file: ../ext/pg.c
